# Generated by Django 4.2.5 on 2023-11-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_car_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100, null=True)),
                ('sage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100, null=True)),
                ('bauthor', models.CharField(max_length=100, null=True)),
                ('students', models.ManyToManyField(to='myapp.students')),
            ],
        ),
    ]
