# Generated by Django 4.2.5 on 2023-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', null=True, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
