# Generated by Django 4.2.5 on 2023-11-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_django_abc_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_abc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.django_abc')),
            ],
        ),
    ]
