# Generated by Django 4.2.5 on 2023-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='django_abc',
            name='des',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='django_abc',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
